listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/config/password_file
acl_file /mosquitto/acl/acl.conf

listener 8883 0.0.0.0
allow_anonymous false
password_file /mosquitto/config/password_file
acl_file /mosquitto/acl/acl.conf
certfile /caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/DUCKDNS_DOMAIN/DUCKDNS_DOMAIN.crt
keyfile /caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/DUCKDNS_DOMAIN/DUCKDNS_DOMAIN.key

persistence true
persistence_location /mosquitto/data/
log_dest stdout
