user saocs_esp32
topic readwrite office/esp32_prototype_01/command
topic readwrite office/esp32_prototype_01/state
topic readwrite office/esp32_prototype_01/status

user saocs_backend
topic readwrite office/+/command
topic readwrite office/+/state
topic readwrite office/+/status
