#!/bin/bash
set -e

echo "============================================"
echo "  SAOCS — OCI VPS Setup Wizard"
echo "============================================"
echo ""
echo "This wizard walks you through setting up the"
echo "OCI Ampere A1 VM for the SAOCS deployment."
echo ""

echo "STEP 1: Verify VM is provisioned"
echo "---------------------------------"
echo "Ensure you have:"
echo "  - OCI Ampere A1 VM (always-free tier)"
echo "  - Reserved static public IP attached"
echo "  - Ubuntu 22.04+ image"
echo ""
read -p "Press Enter when VM is ready..."

echo ""
echo "STEP 2: Firewall — OCI Console"
echo "-------------------------------"
echo "In the OCI Console:"
echo "  1. Go to Compute > Instances > your VM"
echo "  2. Click the Subnet link under Primary VNIC"
echo "  3. Click the Security List"
echo "  4. Add Ingress Rules:"
echo "     - Source CIDR: 0.0.0.0/0"
echo "     - Protocol: TCP"
echo "     - Destination Ports: 80, 443, 8883"
echo "     - Source CIDR: 0.0.0.0/0"
echo "     - Protocol: UDP"
echo "     - Destination Port: 443"
echo ""
read -p "Press Enter when OCI security rules are configured..."

echo ""
echo "STEP 3: Firewall — OS iptables"
echo "-------------------------------"
echo "Run these on the VM:"
echo "  sudo iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT"
echo "  sudo iptables -I INPUT 1 -p tcp --dport 443 -j ACCEPT"
echo "  sudo iptables -I INPUT 1 -p udp --dport 443 -j ACCEPT"
echo "  sudo iptables -I INPUT 1 -p tcp --dport 8883 -j ACCEPT"
echo "  sudo apt install iptables-persistent -y"
echo "  sudo netfilter-persistent save"
echo ""
read -p "Press Enter when iptables rules are saved..."

echo ""
echo "STEP 4: Install Docker"
echo "----------------------"
echo "Run these on the VM:"
echo "  curl -fsSL https://get.docker.com | sh"
echo "  sudo usermod -aG docker \$USER"
echo "  (log out and back in)"
echo "  docker compose version"
echo ""
read -p "Press Enter when Docker is installed..."

echo ""
echo "STEP 5: Create deploy user"
echo "--------------------------"
echo "Run these on the VM:"
echo "  sudo adduser --disabled-password --gecos '' deploy"
echo "  sudo usermod -aG docker deploy"
echo "  sudo mkdir -p /opt/saocs"
echo "  sudo chown deploy:deploy /opt/saocs"
echo ""
read -p "Press Enter when deploy user is created..."

echo ""
echo "STEP 6: SSH key setup"
echo "---------------------"
echo "On your LOCAL machine:"
echo "  ssh-keygen -t ed25519 -f ~/.ssh/saocs_deploy -N ''"
echo "Then copy the PUBLIC key to the VM:"
echo "  ssh-copy-id -i ~/.ssh/saocs_deploy.pub deploy@<VM_IP>"
echo "Add the PRIVATE key content to GitHub:"
echo "  Repository Settings > Secrets > OCI_SSH_PRIVATE_KEY"
echo ""
read -p "Press Enter when SSH key is configured..."

echo ""
echo "STEP 7: Clone repository"
echo "------------------------"
echo "As the deploy user on the VM:"
echo "  cd /opt/saocs"
echo "  git clone https://github.com/saxrael/SAOCS.git ."
echo ""
read -p "Press Enter when repo is cloned..."

echo ""
echo "STEP 8: Create .env"
echo "-------------------"
echo "On the VM, copy the template and fill in real values:"
echo "  cp .env.template .env"
echo "  nano .env"
echo ""
echo "CRITICAL values to set:"
echo "  - JWT_SECRET_KEY (generate: openssl rand -hex 32)"
echo "  - GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET"
echo "  - GOOGLE_REDIRECT_URI (https://<duckdns-domain>/api/auth/google/callback)"
echo "  - FRONTEND_URL (https://<duckdns-domain>)"
echo "  - ALLOWED_ORIGINS (https://<duckdns-domain>)"
echo "  - MQTT_BACKEND_PASSWORD and MQTT_DEVICE_PASSWORD"
echo "  - DUCKDNS_DOMAIN, DUCKDNS_SUBDOMAIN, DUCKDNS_TOKEN"
echo "  - MQTT_BROKER_HOST=mosquitto"
echo "  - ENVIRONMENT=production"
echo ""
read -p "Press Enter when .env is populated..."

echo ""
echo "STEP 9: Generate Mosquitto password file"
echo "-----------------------------------------"
echo "On the VM:"
echo "  docker run --rm -v \$(pwd)/mosquitto/config:/mosquitto/config eclipse-mosquitto:2 \\"
echo "    mosquitto_passwd -c -b /mosquitto/config/password_file saocs_backend <MQTT_BACKEND_PASSWORD>"
echo "  docker run --rm -v \$(pwd)/mosquitto/config:/mosquitto/config eclipse-mosquitto:2 \\"
echo "    mosquitto_passwd -b /mosquitto/config/password_file saocs_esp32 <MQTT_DEVICE_PASSWORD>"
echo ""
read -p "Press Enter when password file is generated..."

echo ""
echo "STEP 10: Configure GitHub Secrets"
echo "----------------------------------"
echo "In GitHub repo Settings > Secrets and variables > Actions:"
echo "  OCI_VM_HOST = <VM's public static IP>"
echo "  OCI_DEPLOY_USER = deploy"
echo "  OCI_SSH_PRIVATE_KEY = <content of ~/.ssh/saocs_deploy>"
echo ""
echo "Configure the 'production' Environment:"
echo "  Settings > Environments > production"
echo "  Required reviewers: your GitHub username"
echo ""
read -p "Press Enter when GitHub secrets are configured..."

echo ""
echo "STEP 11: First deploy"
echo "---------------------"
echo "On the VM:"
echo "  cd /opt/saocs"
echo "  GIT_SHA=\$(git rev-parse HEAD) docker compose build"
echo "  GIT_SHA=\$(git rev-parse HEAD) docker compose up -d"
echo ""
echo "Wait ~30 seconds for Caddy to obtain certificates."
echo "Then verify:"
echo "  curl -sf https://<duckdns-domain>/api/health"
echo "  curl -sf https://<duckdns-domain>/api/version"
echo ""
read -p "Press Enter when first deploy is verified..."

echo ""
echo "STEP 12: Update Mosquitto TLS paths and permissions"
echo "----------------------------------------------------"
echo "After Caddy has obtained certificates, ensure the certificates"
echo "and keys are readable by the Mosquitto service:"
echo "  docker exec saocs-caddy chmod -R a+rX /data/caddy/certificates"
echo ""
echo "Update mosquitto/config/mosquitto.conf with the actual domain:"
echo "  DOMAIN=\$(grep -E '^DUCKDNS_DOMAIN=' .env | cut -d= -f2- | tr -d ' \"\r\n')"
echo "  sed -i \"s/DUCKDNS_DOMAIN/\$DOMAIN/g\" mosquitto/config/mosquitto.conf"
echo ""
echo "Then restart Mosquitto:"
echo "  docker compose restart mosquitto"
echo ""
read -p "Press Enter when Mosquitto TLS is configured..."

echo ""
echo "============================================"
echo "  SETUP COMPLETE"
echo "============================================"
echo ""
echo "Your SAOCS deployment should now be live at:"
echo "  https://<duckdns-domain>"
echo ""
echo "Verify:"
echo "  - Dashboard loads in browser"
echo "  - Login works"
echo "  - MQTT TLS works (ESP32 connects on port 8883)"
echo ""
