[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson@^7.3.1

build_flags =
    -DSERIAL_HARNESS_ENABLED
    -DCORE_DEBUG_LEVEL=0

[env:esp32dev_release]
extends = env:esp32dev
build_flags =
    -DCORE_DEBUG_LEVEL=0
