[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson@^7.3.1

build_flags =
    -DSERIAL_HARNESS_ENABLED
    -DCORE_DEBUG_LEVEL=0

[env:esp32dev_mqtt]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson@^7.3.1
    bertmelis/espMqttClient@^1.7.3

build_flags =
    -DSERIAL_HARNESS_ENABLED
    -DMQTT_ENABLED
    -DCORE_DEBUG_LEVEL=0
    -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -DWIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"
    -DMQTT_BROKER_HOST=\"${sysenv.MQTT_BROKER_HOST}\"
    -DMQTT_BROKER_PORT=1883
    -DMQTT_DEVICE_USER=\"${sysenv.MQTT_DEVICE_USER}\"
    -DMQTT_DEVICE_PASSWORD=\"${sysenv.MQTT_DEVICE_PASSWORD}\"
    -DMQTT_DEVICE_ID=\"${sysenv.MQTT_DEFAULT_DEVICE_ID}\"
    -DOTA_PASSWORD=\"${sysenv.OTA_PASSWORD}\"

[env:esp32dev_release]
extends = env:esp32dev_mqtt
build_flags =
    -DMQTT_ENABLED
    -DCORE_DEBUG_LEVEL=0
    -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -DWIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"
    -DMQTT_BROKER_HOST=\"${sysenv.MQTT_BROKER_HOST}\"
    -DMQTT_BROKER_PORT=1883
    -DMQTT_DEVICE_USER=\"${sysenv.MQTT_DEVICE_USER}\"
    -DMQTT_DEVICE_PASSWORD=\"${sysenv.MQTT_DEVICE_PASSWORD}\"
    -DMQTT_DEVICE_ID=\"${sysenv.MQTT_DEFAULT_DEVICE_ID}\"
    -DOTA_PASSWORD=\"${sysenv.OTA_PASSWORD}\"
